paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
encoding: utf-8

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: GeekProblog

description: Passionate about coding.
author:
  name: Scott Zhou
  email: zhouscott@hotmail.com
  github: godofhand
  linkedin: siyuanzhou
  bio:  The books that you flip today is the money that you calculate tomorrow.


#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH:
